name: CodeSpell
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: CodeSpell
        uses: codespell-project/actions-codespell@3abb875e3aa9713e40eed5aea082672a42f7f95c
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: .codespellignore
