name: CodeSpell
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: CodeSpell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: .codespellignore
