name: Danger
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true
          ruby-version: ruby
      - name: Run Danger
        run: bundle exec danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
